### ISSUE TITLE
Подключить сервис к телеграму

### ISSUE THREAD

**Issue by Tazya** [Tazya/kolesa-upgrade-news-bot#5]
Родительская задача:
-  #3 

Цель: Сервис должен уметь взаимодействовать с чат-ботом в Телеграме.

Создать бота через BotFather и подключить его в наш сервис
У бота должен быть хендлер на команду `/hello`. В ответ бот должен выводить имя пользователя и приветственное сообщение.

Подключение к боту мы уже выполняли в лекции, достаточно будет повторить: https://github.com/Kolesa-Education/go-telegram-bot

Библиотека для работы с api Telegram https://github.com/tucnak/telebot

**Comment by FishSev** [comment]
Задачу выполнил
